### ISSUE TITLE
Addon not loaded

### ISSUE THREAD

**Issue by Lapin42** [iMintty/TRP3-Location-Toggle#5]
![image](https://user-images.githubusercontent.com/132603784/236282563-f136acc4-1393-4405-acb1-74246756794c.png)

![image](https://user-images.githubusercontent.com/132603784/236283052-7800431f-06c7-4b88-9d72-d903126e4b61.png)

The addon not loaded and it's not my job to change the wrong lines of code. I'm not a programmer just a gamer and it bothers me a lot to have to do the work by myself. It might be better to have an update.

**Comment by reed216** [comment]
fixed by #4
