### ISSUE TITLE
Button does not show up in TRP

### ISSUE THREAD

**Issue by RePeterCSA** [iMintty/TRP3-Location-Toggle#6]
The issue is, after downloading and loading the addon through Curseforge, it does not show the button after the latest update. There is no error, no message, addon is loaded fine. Tried reintalling, uninstalling and installing, reloading in game. Nothing works

**Comment by praetoras** [comment]
I just wanted to note that I am having a similar issue. In my case, however, it is actually showing an error every time the interface loads. It mentions line 25, an issue with a name and group. I will get the exact error later if I can.

**Comment by reed216** [comment]
fixed by #4
