### ISSUE TITLE
[BugSack] Retail 11.0.0 - Incompatibility Error - new, major TRP3 update

### ISSUE THREAD

**Issue by Raiukage** [iMintty/TRP3-Location-Toggle#7]
[TRP3.txt](https://github.com/user-attachments/files/16357302/TRP3.txt)

Getting this persistent error, game is being bogged down with the addon activated, will need to remove until fixed.

**Comment by StraythePath** [comment]
GetMouseFocus is depreciated as of 11.0
If the author doesn't get around to it, you can fix it yourself by opening the lua and replacing 'GetMouseFocus' with 'GetMouseFoci'

**Comment by reed216** [comment]
I’ll get this patched this week when I get a free half an hour
